services:
  app:
    restart: always
    build: .
    environment:
      - JUPYTER_TOKEN=token
      - TF_GPU_ALLOCATOR=cuda_malloc_async
      - TF_FORCE_GPU_ALLOW_GROWTH=true
      - TF_CPP_MAX_VLOG_LEVEL=3
    ports:
      - "8888:8888"
      - "6006:6006"
    volumes:
      - .:/app
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
